# HW04 - Exploring Trees/Graphs

YOUR NAME: Alan Hahn

Some facts about trees:
+ A tree is connected and contains no cycles (by definition).
+ A tree with *n* nodes has *n* - 1 edges.
+ Every node in a tree except the root has a single parent.
+ In a tree, there is a unique path between every pair of nodes. In particular, there is a unique path of ancestors from every node to the root.

In this exercise, we use Python dictionaries to represent trees, rather than constructing the linked structures explicitly. Each dictionary entry maps a parent node to a list of its children.

In [1]:
k = set()
print(k)
k.add('x')
k.add('y')
t = set()
t.add('z')
t.add('x')
k.add('x')

#k.remove('y')
print(k)
print(t)
print(t-k)
print(t-k == set())

set()
{'x', 'y'}
{'x', 'z'}
{'z'}
False


In [2]:
# here is a list of edges (parent, child):
T = [('Bob','Eve'),('Alice','Carol'),('Eve','Frank'),('Alice','Doug'),('Frank','Ginger'), \
         ('Eve','Howard'),('Carol','Irene'),('Frank','Jeff'),('Doug','Kathy'),('Bob','Luis'), \
         ('Alice','Bob'),('Bob','Mabel'),('Ginger','Norm'),('Howard','Oprah'),('Carol','Peter'), \
         ('Kathy','Queen'),('Mabel','Ursala'),('Luis','Ronald'),('Ginger','Sarah'),('Irene','Tom'), \
         ('Jeff','Vince'),('Peter','Wanda'),('Oprah','Xanthia'),('Norm','Yaakov'),('Luis','Zandra')]

print ('T has',len(T),'edges')
vertices = set()
for edge in T:
    s,t = edge
    vertices.add(s)
    vertices.add(t)
print ('T has',len(vertices),'vertices')

T has 25 edges
T has 26 vertices


So this could be a tree. Now lets compute the number of parents for each vertex. The result confirms that we indeed have a tree and that the root is Alice (right?).

In [3]:
np = {}
for v in vertices:
    np[v] = 0
for parent,child in T:
    np[child] += 1
print (np)

{'Peter': 1, 'Frank': 1, 'Oprah': 1, 'Doug': 1, 'Ginger': 1, 'Wanda': 1, 'Ronald': 1, 'Carol': 1, 'Norm': 1, 'Irene': 1, 'Vince': 1, 'Sarah': 1, 'Bob': 1, 'Kathy': 1, 'Xanthia': 1, 'Mabel': 1, 'Eve': 1, 'Luis': 1, 'Howard': 1, 'Jeff': 1, 'Zandra': 1, 'Ursala': 1, 'Tom': 1, 'Yaakov': 1, 'Alice': 0, 'Queen': 1}


We now construct a dictionary of pairs (p,c) where p is the parent of the list of children c

In [4]:
adjacency_map = {}
for v in vertices:
    adjacency_map[v] = []
for p,c in T:
    adjacency_map[p].append(c)

print ("node and children:")
for p in adjacency_map:
    print (p, ":", adjacency_map[p])

print ()
print (adjacency_map)

node and children:
Peter : ['Wanda']
Frank : ['Ginger', 'Jeff']
Oprah : ['Xanthia']
Doug : ['Kathy']
Ginger : ['Norm', 'Sarah']
Wanda : []
Ronald : []
Carol : ['Irene', 'Peter']
Norm : ['Yaakov']
Irene : ['Tom']
Vince : []
Sarah : []
Bob : ['Eve', 'Luis', 'Mabel']
Kathy : ['Queen']
Xanthia : []
Mabel : ['Ursala']
Eve : ['Frank', 'Howard']
Luis : ['Ronald', 'Zandra']
Howard : ['Oprah']
Jeff : ['Vince']
Zandra : []
Ursala : []
Tom : []
Yaakov : []
Alice : ['Carol', 'Doug', 'Bob']
Queen : []

{'Peter': ['Wanda'], 'Frank': ['Ginger', 'Jeff'], 'Oprah': ['Xanthia'], 'Doug': ['Kathy'], 'Ginger': ['Norm', 'Sarah'], 'Wanda': [], 'Ronald': [], 'Carol': ['Irene', 'Peter'], 'Norm': ['Yaakov'], 'Irene': ['Tom'], 'Vince': [], 'Sarah': [], 'Bob': ['Eve', 'Luis', 'Mabel'], 'Kathy': ['Queen'], 'Xanthia': [], 'Mabel': ['Ursala'], 'Eve': ['Frank', 'Howard'], 'Luis': ['Ronald', 'Zandra'], 'Howard': ['Oprah'], 'Jeff': ['Vince'], 'Zandra': [], 'Ursala': [], 'Tom': [], 'Yaakov': [], 'Alice': ['Carol', 'Doug'

In [6]:
# Example of string replication

print (5*"Hello!")

Hello!Hello!Hello!Hello!Hello!


In [7]:
# A recursive Depth-First traversal of a tree defined by an adjacency_map
def print_tree_depth_first(parent, adjacency_map, level=0):
    print (level*'| '+ str(parent))
    children = adjacency_map[parent]
    for child in children:
        print_tree_depth_first(child, adjacency_map, level+1)

root = 'Alice'
print_tree_depth_first(root, adjacency_map)

Alice
| Carol
| | Irene
| | | Tom
| | Peter
| | | Wanda
| Doug
| | Kathy
| | | Queen
| Bob
| | Eve
| | | Frank
| | | | Ginger
| | | | | Norm
| | | | | | Yaakov
| | | | | Sarah
| | | | Jeff
| | | | | Vince
| | | Howard
| | | | Oprah
| | | | | Xanthia
| | Luis
| | | Ronald
| | | Zandra
| | Mabel
| | | Ursala


## Question 1
Extend the following breadth-first traversal function to include the generation, so that the output is like below. Do this by storing a tuple with generation and node in the queue.

In [8]:
from collections import deque 

# breadth-first traversal using a queue
def print_tree_breath_first(root, adjacency_map):
    Q = deque()
    Q.append((root,0))
    i = 0
    while len(Q)>0:
        (p,i) = Q.popleft()
        print(p,i) 
        children = adjacency_map[p]
        for child in children:
            Q.append((child,i+1))

print_tree_breath_first("Alice", adjacency_map)

Alice 0
Carol 1
Doug 1
Bob 1
Irene 2
Peter 2
Kathy 2
Eve 2
Luis 2
Mabel 2
Tom 3
Wanda 3
Queen 3
Frank 3
Howard 3
Ronald 3
Zandra 3
Ursala 3
Ginger 4
Jeff 4
Oprah 4
Norm 5
Sarah 5
Vince 5
Xanthia 5
Yaakov 6


## Question 2
Write a function that checks if for the given directed graph (given by a list of edges E) root is connected to every other vertex.

In [9]:
def all_connected_to(edge_list, root):
    """ return true if you can reach all nodes in the graph given
    by a list of edges (edge_list) can be reached by root """
    
    vertices = set()
    for edge in edge_list:
        s,t = edge
        vertices.add(s)
        vertices.add(t)
    
    adjacency_map = {}
    for v in vertices:
        adjacency_map[v] = []
    for p,c in edge_list:
        adjacency_map[p].append(c)   
        
    s = set()
    Q = deque()
    Q.append(root)
    while len(Q)>0:                  #find all vertices that may be reached by the input vertex
        i = Q.popleft()              #along directed edges, and keep a set containing all of the vertices
        s.add(i)                     #seen. Return whether this set equals the set of vertices of the graph 
        children = adjacency_map[i]
        for child in children:
            if child not in s:
                Q.append(child)
            
    # start by constructing set of vertices and a dictionary for looking up children
    
    #print 's =', s, 'v = ', vertices
    return (vertices == s)

# This function runs in time O(n^2)
# popping and appending from deque takes O(1) time, adding to a set takes O(1) time. For each vertex,
#we check to see if the vertex is in a set, which takes O(n) time, so over all vertices is O(n^2). So the
#order is O(n^2)
    

In [10]:
G = [("A","B"), ("B","C")]
print (all_connected_to(G, "A"))
G2 = [("1","2"), ("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G2, "A"))
print (all_connected_to(G2, "1"))
G3 = [("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G3, "C"))
 #and our graph from above?
print (all_connected_to(T, "Alice"))

True
False
False
True
True


## Question 3
We now treat the graph T from above as undirected (edges going in both directions) and construct a tree rooted in Bob. The tree will contain edges from a vertex to the parent and direct children. The result will tell us how far removed the vertices are from our root Bob.

In [12]:
root = 'Bob'

# construct adjacency for graph T:
adjacency_map = {}
for vertex in vertices:
    adjacency_map[vertex] = []
for edge in T:
    s,t = edge
    adjacency_map[s].append(t)
    adjacency_map[t].append(s)
    
print ("parents/children of Ginger:",adjacency_map['Ginger'])
print
print (adjacency_map)

# now create tree as a dictionary "n maps to children(n)"
print


            
tree = {}       
s = set()
Q = deque()
Q.append(root)
for v in vertices:
    tree[v] = []
while len(Q)>0:                        #for a given vertex, add all children of the vertex to the new 
    p = Q.popleft()                    #adjacency map called tree, but only add vertices if you haven't
    s.add(p)                           #already seen them before, as if you've seen them before, they are
    children = adjacency_map[p]        #the parent and not a child. 
    for child in children:
        if child not in s:
            Q.append(child)
            tree[p].append(child)           
            
            
print
print (tree)


parents/children of Ginger: ['Frank', 'Norm', 'Sarah']
{'Peter': ['Carol', 'Wanda'], 'Frank': ['Eve', 'Ginger', 'Jeff'], 'Oprah': ['Howard', 'Xanthia'], 'Doug': ['Alice', 'Kathy'], 'Ginger': ['Frank', 'Norm', 'Sarah'], 'Wanda': ['Peter'], 'Ronald': ['Luis'], 'Carol': ['Alice', 'Irene', 'Peter'], 'Norm': ['Ginger', 'Yaakov'], 'Irene': ['Carol', 'Tom'], 'Vince': ['Jeff'], 'Sarah': ['Ginger'], 'Bob': ['Eve', 'Luis', 'Alice', 'Mabel'], 'Kathy': ['Doug', 'Queen'], 'Xanthia': ['Oprah'], 'Mabel': ['Bob', 'Ursala'], 'Eve': ['Bob', 'Frank', 'Howard'], 'Luis': ['Bob', 'Ronald', 'Zandra'], 'Howard': ['Eve', 'Oprah'], 'Jeff': ['Frank', 'Vince'], 'Zandra': ['Luis'], 'Ursala': ['Mabel'], 'Tom': ['Irene'], 'Yaakov': ['Norm'], 'Alice': ['Carol', 'Doug', 'Bob'], 'Queen': ['Kathy']}
{'Peter': ['Wanda'], 'Frank': ['Ginger', 'Jeff'], 'Oprah': ['Xanthia'], 'Doug': ['Kathy'], 'Ginger': ['Norm', 'Sarah'], 'Wanda': [], 'Ronald': [], 'Carol': ['Irene', 'Peter'], 'Norm': ['Yaakov'], 'Irene': ['Tom'], 'Vince': [

Execute the following two blocks to check your result:

In [13]:
print_tree_depth_first(root, tree)

Bob
| Eve
| | Frank
| | | Ginger
| | | | Norm
| | | | | Yaakov
| | | | Sarah
| | | Jeff
| | | | Vince
| | Howard
| | | Oprah
| | | | Xanthia
| Luis
| | Ronald
| | Zandra
| Alice
| | Carol
| | | Irene
| | | | Tom
| | | Peter
| | | | Wanda
| | Doug
| | | Kathy
| | | | Queen
| Mabel
| | Ursala


In [17]:
print_tree_breath_first(root, tree)

Bob 0
Eve 1
Luis 1
Alice 1
Mabel 1
Frank 2
Howard 2
Ronald 2
Zandra 2
Carol 2
Doug 2
Ursala 2
Ginger 3
Jeff 3
Oprah 3
Irene 3
Peter 3
Kathy 3
Norm 4
Sarah 4
Vince 4
Xanthia 4
Tom 4
Wanda 4
Queen 4
Yaakov 5


## Question 4: n queens problem
Backtracking is the technique of recursively exploring the tree that contains all the possible solutions to a problem. Choose a systematic way to explore all the possible cases. This approach should reflect a rooted tree, and the backtracking approach is a depth-first search of the rooted tree. Whenever the search has found a solution or determined that there are no further solutions on the branches below the current vertex, backtrack to the preceeding vertex. 

A classic example of a problem that can be easily solved with this approach is the n queens problem.  This problem is to determine all the possible ways to place n nonattacking queens on an n-by-n chess board. The following code provides two helpful routines for this problem and illustrates one of the solutions for the 4 queens problem.

In [18]:
import numpy as np
import copy

def build_chessboard(N):
    chessboard = np.zeros((N,N))
    return chessboard

def print_chessboard(chessboard):
    N = len(chessboard)
    for r in range(N):
        for c in range(N):
            if chessboard[r,c] == 1:
                print ('Q'),
            else:
                print ('.'),
        print ()
    print ()

# generate an empty 4x4 chessboard:
chessboard = build_chessboard(4)
print (chessboard)

# Place 4 non-attacking queens on this board
chessboard[1,0] = 1
chessboard[3,1] = 1
chessboard[0,2] = 1
chessboard[2,3] = 1

# Pretty print the resulting board
print_chessboard(chessboard)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
.
.
Q
.

Q
.
.
.

.
.
.
Q

.
Q
.
.




Complete the following code to solve the n queens problem by returning the total number of solutions while printing only the first five solutions.

In [19]:
def n_queens(chessboard, col=0, count=0):
    """ given a partially filled <chessboard>, try to place a queen in column <col> and recursively fill the board.
    Finally return the number of solutions (added to <count>)"""
    N = len(chessboard)
    if col == N:
        if count < 5:
            print_chessboard(chessboard)
        return count+1
    
    # Examine all available squares in column <col> (value is 0), place the queen, and 
    # mark all squares under attack by that queen (use anything except 0 or 1).
    # Note: you can make a copy of a chessboard using chessboard.copy()
    #
    
    
    for i in range(N):
        if chessboard[i,col]!= 3:
            cb = chessboard.copy()
            cb[i,col] = 1
            j,l = copy.copy(i), copy.copy(col)
            k = 1
            while l!= N-1:
                l+=k
                cb[j,l] = 3
            j,l = copy.copy(i), copy.copy(col)
            while j!=0 and l!=N-1:
                j-=k
                l+=k
                cb[j,l] = 3
            j,l = copy.copy(i), copy.copy(col)
            while j!=N-1 and l!=N-1:
                j+=k
                l+=k
                cb[j,l] = 3
            count = n_queens(cb,col+1,count)
    
    
    
    
    
    #count = n_queens(newboard,col+1,count)
    return count

chessboard = build_chessboard(5)
count = n_queens(chessboard)
print ("solutions: ", count)

Q
.
.
.
.

.
.
.
Q
.

.
Q
.
.
.

.
.
.
.
Q

.
.
Q
.
.


Q
.
.
.
.

.
.
Q
.
.

.
.
.
.
Q

.
Q
.
.
.

.
.
.
Q
.


.
.
Q
.
.

Q
.
.
.
.

.
.
.
Q
.

.
Q
.
.
.

.
.
.
.
Q


.
.
.
Q
.

Q
.
.
.
.

.
.
Q
.
.

.
.
.
.
Q

.
Q
.
.
.


.
Q
.
.
.

.
.
.
Q
.

Q
.
.
.
.

.
.
Q
.
.

.
.
.
.
Q


solutions:  10


In [20]:
chessboard = build_chessboard(1)
count = n_queens(chessboard)
print ("solutions: ", count)
chessboard = build_chessboard(2)
count = n_queens(chessboard)
print ("solutions: ", count)
chessboard = build_chessboard(3)
count = n_queens(chessboard)
print ("solutions: ", count)
chessboard = build_chessboard(4)
count = n_queens(chessboard)
print ("solutions: ", count)

Q


solutions:  1
solutions:  0
solutions:  0
.
.
Q
.

Q
.
.
.

.
.
.
Q

.
Q
.
.


.
Q
.
.

.
.
.
Q

Q
.
.
.

.
.
Q
.


solutions:  2


In [21]:
def test(cb):
    cb[0,0]=1
    print_chessboard(cb)
    
chessboard = build_chessboard(4)
print_chessboard(chessboard)
test(chessboard.copy())# try chessboard.copy() instead
print_chessboard(chessboard)  # oooops!

.
.
.
.

.
.
.
.

.
.
.
.

.
.
.
.


Q
.
.
.

.
.
.
.

.
.
.
.

.
.
.
.


.
.
.
.

.
.
.
.

.
.
.
.

.
.
.
.




In [26]:
import copy

# copy makes a copy of the outer-most object, but keeps the same references to the inner
# object.
a=[2,4,[6]]
print ("before: a=", a)

b=copy.copy(a)
b[0]+=1
b[2][0]+=1

print ("after: a=",a," b=", b, " (using copy)")

# deepcopy also makes a copy of each contained element (recursively)
a=[2,4,[6]]
b=copy.deepcopy(a)
b[0]+=1
b[2][0]+=1
print ("after: a=",a," b=", b, " (using deepcopy)")


before: a= [2, 4, [6]]
after: a= [2, 4, [7]]  b= [3, 4, [7]]  (using copy)
after: a= [2, 4, [6]]  b= [3, 4, [7]]  (using deepcopy)
